version: '3.1'

services:
  db:
    container_name: mysql-db-container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user-db
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306